title: Jhimy F. Villar
email: stjhimy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My life, my code and everything between it.
permalink: /posts/:year-:month-:day-:title/
twitter_username: stjhimy
github_username: stjhimy
instagram_username: stjhimy
google_analytics: UA-15988274-3

# Build settings
markdown: kramdown
theme: jekyll-flat

gems:
  - jekyll-sitemap
