gems:
  - jekyll-paginate
  - jekyll-sitemap
title: Jhimy F. Villar
email: stjhimy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My life, my code and everything between it.
url: "http://stjhimy.com" # the base hostname & protocol for your site
permalink: /posts/:year-:month-:day-:title/

# Build settings
markdown: kramdown
paginate: 3
paginate_path: "/posts/page/:num"
