# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
gems:
  - jekyll-paginate
  - jekyll-sitemap
title: Jhimy F. Villar
email: stjhimy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My life, my code and everything between it.
url: "http://stjhimy.com" # the base hostname & protocol for your site
twitter_username: stjhimy
github_username:  stjhimy
permalink: /posts/:year-:month-:day-:title/

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page/:num"
